# global Config
projectname: 'Mini_Project'
data_style: 'coco'
cuda: False
tensorboard: True

# Config DataLoader
root_dir: 'C:\\Users\\jsk\\data\\study_miniproject'
batch_size: 4
start_epoch: 0
epoch: 30
resize: [28, 28]
num_worker: 4
pin_memory: True

# Config model
model: 'retinanet'
depth: 18 # resnet backbone - 18, 34, 50, 101, 152
resume:
lr: 0.00001
